### ISSUE TITLE
interactive document.readyState

### ISSUE THREAD

**Issue by sudo-suhas** [sindresorhus/dom-loaded#1]
Should the `document.readyState` be checked for `interactive`? Refer - http://beeker.io/jquery-document-ready-equivalent-vanilla-javascript.

**Comment by sindresorhus** [comment]
No, this package targets modern browsers. `interactive` isn't even a state in Chrome.

**Comment by sholladay** [comment]
I just checked and Chrome definitely does have `interactive`, in accordance with [the spec](https://www.w3.org/TR/html5/dom.html#resource-metadata-management). @sindresorhus I believe you may have been thinking of IE's obsolete `loaded` ready state.

Try this reproduction example. I used [deelay.me](http://www.deelay.me/) to simulate a slow loading image. So the document parses much faster than it loads, thus allowing you to watch the states change.

```html
<!DOCTYPE html>
<html>
    <body>
        <p>This should parse quickly but load slowly.</p>
        <img src="http://deelay.me/5000/https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Example.tiff/lossless-page1-128px-Example.tiff.png" />
        <script>
            console.log('initial state:', document.readyState);
            document.onreadystatechange = function () {
                console.log('state changed:', document.readyState);
            }
        </script>
    </body>
</html>
```

This library has a bug where the promise will never resolve if it runs after `DOMContentLoaded` but before the ready state is `complete` (i.e. before the image has finished loading).

There are two easy solutions:

1. Change the event listener to listen for the [`load`](https://developer.mozilla.org/en-US/docs/Web/Events/load) event, rather than [`DOMContentLoaded`](https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded). This seems the most semantically appropriate for this library, but it is slower in the sense that the promise will always wait for sub-resources, like images, to load.
2. Add `interactive` as a valid `readyState` to resolve. This is probably what people want most of the time, for the promise to only wait for the document to be parsed. But then the library should probably be renamed to `dom-parsed` or something.

**Comment by sindresorhus** [comment]
@sholladay Thanks for the info. I think I was confused by the `interactive` state never showing up.

> But then the library should probably be renamed to dom-parsed or something.

It's DOM loaded, not page loaded.
